enable-module-update = true
parallel-jobs = 1

[YouTube]
enabled = true
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Twitter]
patches-source = "crimera/piko-newx"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
version = "latest"
included-patches = "'NewX: Restore Twitter branding'"

[Music]
enabled = false

[Reddit-Morphe]
enabled = false

[GooglePhotos]
enabled = false

[Twitch]
enabled = false
